DROP USER IF EXISTS "dev_entechlog_demo_user";
DROP USER IF EXISTS "dev_svc_entechlog_snow_atlan_user";
DROP USER IF EXISTS "dev_svc_entechlog_snow_dbt_user";
DROP USER IF EXISTS "dev_svc_entechlog_snow_kafka_user";

DROP ROLE IF EXISTS DEV_ENTECHLOG_DEMO_ROLE;
DROP ROLE IF EXISTS DEV_SVC_ENTECHLOG_SNOW_ATLAN_ROLE;
DROP ROLE IF EXISTS DEV_SVC_ENTECHLOG_SNOW_DBT_ROLE;
DROP ROLE IF EXISTS DEV_SVC_ENTECHLOG_SNOW_KAFKA_ROLE;
DROP ROLE IF EXISTS ENTECHLOG_DE_ROLE;
DROP ROLE IF EXISTS ENTECHLOG_DA_ROLE;

DROP DATABASE IF EXISTS "DEV_ENTECHLOG_DW_DB";
DROP DATABASE IF EXISTS "DEV_ENTECHLOG_PREP_DB";
DROP DATABASE IF EXISTS "DEV_ENTECHLOG_RAW_DB";

DROP WAREHOUSE IF EXISTS "ALL_ENTECHLOG_QUERY_WH_XS";
DROP WAREHOUSE IF EXISTS "DEV_ENTECHLOG_DBT_WH_XS";
DROP WAREHOUSE IF EXISTS "DEV_ENTECHLOG_DEMO_WH_XS";