DROP USER ENTECHLOG_ATLAN_USER;
DROP USER ENTECHLOG_DBT_USER;
DROP USER ENTECHLOG_KAFKA_USER;

DROP ROLE ENTECHLOG_ANALYST_ROLE;
DROP ROLE ENTECHLOG_ATLAN_ROLE;
DROP ROLE ENTECHLOG_DBT_ROLE;
DROP ROLE ENTECHLOG_KAFKA_ROLE;
