DROP USER ENTECHLOG_ATLAN_USER;
DROP USER ENTECHLOG_DBT_USER;
DROP USER ENTECHLOG_KAFKA_USER;

DROP ROLE IF EXISTS ENTECHLOG_DA_ROLE;
DROP ROLE IF EXISTS SVC_ENTECHLOG_SNOW_ATLAN_ROLE;
DROP ROLE IF EXISTS SVC_ENTECHLOG_SNOW_DBT_ROLE;
DROP ROLE IF EXISTS SVC_ENTECHLOG_SNOW_KAFKA_ROLE;

DROP DATABASE IF EXISTS "DEV_ENTECHLOG_DW_DB";
DROP DATABASE IF EXISTS "DEV_ENTECHLOG_PREP_DB";
DROP DATABASE IF EXISTS "DEV_ENTECHLOG_RAW_DB";

DROP WAREHOUSE IF EXISTS "ALL_ENTECHLOG_QUERY_WH_XS";
DROP WAREHOUSE IF EXISTS "DEV_ENTECHLOG_DBT_WH_XS";
DROP WAREHOUSE IF EXISTS "DEV_ENTECHLOG_DEMO_WH_XS";