// Create role and grant required access for TF to operate
CREATE ROLE IF NOT EXISTS ENTECHLOG_TERRAFORM;
GRANT ROLE SECURITYADMIN TO ROLE ENTECHLOG_TERRAFORM;
GRANT ROLE SYSADMIN TO ROLE ENTECHLOG_TERRAFORM;

// Grant role to TF user
create user IF NOT EXISTS TERRAFORM_USER password='tfuser' default_role = ENTECHLOG_TERRAFORM;

GRANT ROLE ENTECHLOG_TERRAFORM TO USER TERRAFORM_USER;
