// Create role and grant required access for TF to operate
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS ENTECHLOG_TERRAFORM_ROLE;

USE ROLE SYSADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE ENTECHLOG_TERRAFORM_ROLE;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE ENTECHLOG_TERRAFORM_ROLE;

// Grant role to TF user
USE ROLE USERADMIN;
CREATE USER IF NOT EXISTS DEV_ENTECHLOG_TF_USER PASSWORD='tfuser' DEFAULT_ROLE = ENTECHLOG_TERRAFORM_ROLE;
GRANT ROLE ENTECHLOG_TERRAFORM_ROLE TO USER DEV_ENTECHLOG_TF_USER;
GRANT CREATE ROLE ON ACCOUNT TO ROLE ENTECHLOG_TERRAFORM_ROLE;
GRANT CREATE USER ON ACCOUNT TO ROLE ENTECHLOG_TERRAFORM_ROLE;