DROP DATABASE IF EXISTS TST_ENTECHLOG_RAW_DB;
DROP DATABASE IF EXISTS TST_ENTECHLOG_PREP_DB;
DROP DATABASE IF EXISTS TST_ENTECHLOG_DW_DB;

DROP WAREHOUSE IF EXISTS TST_ENTECHLOG_DBT_WH_XS;
DROP WAREHOUSE IF EXISTS TST_ENTECHLOG_STREAMLIT_WH_XS;

DROP USER IF EXISTS TST_ENTECHLOG_DBT_USER;
DROP ROLE IF EXISTS TST_ENTECHLOG_DBT_ROLE;

DROP USER IF EXISTS TST_ENTECHLOG_STREAMLIT_USER;
DROP ROLE IF EXISTS TST_ENTECHLOG_STREAMLIT_ROLE;