DROP DATABASE IF EXISTS "TST_ENTECHLOG_DW_DB";
DROP DATABASE IF EXISTS "TST_ENTECHLOG_PREP_DB";
DROP DATABASE IF EXISTS "TST_ENTECHLOG_RAW_DB";

DROP WAREHOUSE IF EXISTS "TST_ENTECHLOG_DBT_WH_XS";
DROP WAREHOUSE IF EXISTS "ALL_ENTECHLOG_QUERY_WH_XS";

DROP USER IF EXISTS "demo.analyst@example.com";
DROP USER IF EXISTS "demo.dev@example.com";
DROP USER IF EXISTS "tst_entechlog_dbt_user";

DROP ROLE IF EXISTS "TST_ENTECHLOG_DBT_ROLE";

DROP INTEGRATION IF EXISTS "TST_ENTECHLOG_STR_S3_INTG";