GRANT CREATE STAGE ON schema "TST_ENTECHLOG_RAW_DB"."CRICSHEET" TO ROLE ENTECHLOG_TERRAFORM_ROLE;
GRANT CREATE FILE FORMAT ON schema "TST_ENTECHLOG_RAW_DB"."CRICSHEET" TO ROLE ENTECHLOG_TERRAFORM_ROLE;
