-- Create role and user
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS DEV_ENTECHLOG_STREAMLIT_ROLE;
CREATE USER IF NOT EXISTS DEV_ENTECHLOG_STREAMLIT_USER DEFAULT_ROLE = DEV_ENTECHLOG_STREAMLIT_ROLE;
GRANT ROLE DEV_ENTECHLOG_STREAMLIT_ROLE TO USER DEV_ENTECHLOG_STREAMLIT_USER;

ALTER USER DEV_ENTECHLOG_STREAMLIT_USER SET PASSWORD = '<password>';

-- Create warehouse
USE ROLE SYSADMIN;

CREATE OR REPLACE WAREHOUSE DEV_ENTECHLOG_STREAMLIT_WH_XS
WITH 
WAREHOUSE_SIZE = 'XSMALL' 
WAREHOUSE_TYPE = 'STANDARD' 
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE 
MIN_CLUSTER_COUNT = 1 
MAX_CLUSTER_COUNT = 1
SCALING_POLICY = 'ECONOMY' 
COMMENT = 'Warehouse for streamlit';

CREATE DATABASE IF NOT EXISTS DEV_ENTECHLOG_RAW_DB;
CREATE SCHEMA IF NOT EXISTS DEV_ENTECHLOG_RAW_DB.YELLOW_CAB;

--GRANT required access to the role
GRANT USAGE ON WAREHOUSE DEV_ENTECHLOG_STREAMLIT_WH_XS TO ROLE DEV_ENTECHLOG_STREAMLIT_ROLE;

--GRANT USAGE ON DATABASE DEV_ENTECHLOG_RAW_DB TO ROLE DEV_ENTECHLOG_STREAMLIT_ROLE;
--GRANT ALL ON SCHEMA DEV_ENTECHLOG_RAW_DB.YELLOW_CAB TO DEV_ENTECHLOG_STREAMLIT_ROLE;

-- Get account ID
SELECT CURRENT_ACCOUNT();

-- Premissions related to dim and fact table access
GRANT USAGE ON DATABASE dev_entechlog_dw_db TO DEV_ENTECHLOG_STREAMLIT_ROLE;
GRANT USAGE ON SCHEMA dev_entechlog_dw_db.dim TO DEV_ENTECHLOG_STREAMLIT_ROLE;
GRANT USAGE ON SCHEMA dev_entechlog_dw_db.fact TO DEV_ENTECHLOG_STREAMLIT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA dev_entechlog_dw_db.dim TO DEV_ENTECHLOG_STREAMLIT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA dev_entechlog_dw_db.fact TO DEV_ENTECHLOG_STREAMLIT_ROLE;